language: python
cache:
  timeout: 1800
  pip: true

# https://docs.travis-ci.com/user/languages/python/

jobs:
  include:
    - name: "Python 3.6 on Ubuntu"
      os: linux
      python: 3.6
      before_install:
        -  sudo apt-get install -y ffmpeg
    - name: "Python 3.7 on macOS 10.14"
      os: osx
      osx_image: xcode11.2
      language: shell
      before_install:
        - brew install ffmpeg
    - name: "Python 3.8 on Windows"
      os: windows
      language: shell
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
         - choco install python --version 3.8.0
         - choco install ffmpeg
         # - choco install miktex.portable
         - choco install sox.portable
         - python -m pip install --upgrade pip

install:
  - pip3 install --upgrade pip
  - pip3 install wheel
  - pip3 install -r requirements.txt || pip3 install -r requirements.txt --user
  - pip3 install -r tests/requirements.txt || pip3 install -r tests/requirements.txt --user
  - python3 setup.py install

script:
  - ipython -m pytest -- --cov=.

after_success:
  - codecov
