language: python
cache:
  timeout: 1800
  pip: true

jobs:
  include:
    - os: linux
      python: 3.6
      before_install:
        -  choco install python --version 3.8.0
    - os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell
      before_install:
        - brew install ffmpeg
    - os: windows
      python: 3.8
      before_install:
         - choco install python --version 3.8.0
         - choco install ffmpeg
         - choco install miktex
         - choco install sox.portable

install:
  - pip install wheel
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - python setup.py install

script:
  - ipython -m pytest -- --cov=.

after_success:
  - codecov
