language: python
cache:
  timeout: 1800
  pip: true

jobs:
  include:
    - name: "Python 3.6 on Ubuntu"
      os: linux
      python: 3.6
      before_install:
        -  sudo apt-get install -y ffmpeg
    - name: "Python 3.7 on macOS 10.14"
      os: osx
      osx_image: xcode11.2
      language: shell
      before_install:
        - brew install ffmpeg
        - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        - python3 get-pip.py
    - name: "Python 3.8 on Windows"
      os: windows
      language: shell
      before_install:
         - choco install python --version 3.8.0
         - choco install ffmpeg
         - choco install miktex.install
         - choco install sox.portable

install:
  - pip install wheel --user
  - pip install -r requirements.txt --user
  - pip install -r tests/requirements.txt --user
  - python3 setup.py install

script:
  - ipython -m pytest -- --cov=.

after_success:
  - codecov
